### ISSUE TITLE
The Manjaro Problem 

### ISSUE THREAD

**Issue by emo-mruczek** [CharlotteCross1998/linuwux#14]
I think that a name chosen for Manjaro is a missed opportunity. It should be Nyanjaro. @kanapka0 @jacekpoz agrees.

**Comment by imnotpoz** [comment]
I agree, nyanjaro is a much better name

@Omikorin please confirm your agreement:
![image](https://github.com/CharlotteCross1998/linuwux/assets/64381190/d638fad0-693f-4c3e-ac72-214a529fafc8)

**Comment by CharlotteCross1998** [comment]
This absolutely has been a missed opportunity and I cannot believe my initial filename was *that*. I could have gone for Manjarowo too.

**Comment by Omikorin** [comment]
I agree.

**Comment by kanapka0** [comment]
Agreement

**Comment by imnotpoz** [comment]
@CharlotteCross1998 thank you for solving the manjaro problem so fast!

**Comment by CharlotteCross1998** [comment]
@jacekpoz I'm actually quite embarrassed at the initial filename, that was horrible lol

**Comment by imnotpoz** [comment]
it's ok

**Comment by MicroPanda123** [comment]
I disagree because including Manjaro is an insult to whole Linuwux community regardless of naming :+1:

**Comment by CharlotteCross1998** [comment]
> I disagree because including Manjaro is an insult to whole Linuwux community regardless of naming 👍

Manjarno
